#!/usr/bin/env python3
"""Regenerate docs/implementation/SRC_INDEX.md from the tracked src/ tree.

Usage:
  python scripts/generate_implementation_index.py
      Write SRC_INDEX.md (default).

  python scripts/generate_implementation_index.py --check
      Exit 0 only if SRC_INDEX.md is already up to date (CI / pre-commit).

See docs/implementation/README.md and spec/00_core/implementation_doc_mirror.md.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - dev env should have pyyaml
    yaml = None  # type: ignore[assignment]


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
IMPL_SRC = REPO_ROOT / "docs" / "implementation" / "src"
OUTPUT = REPO_ROOT / "docs" / "implementation" / "SRC_INDEX.md"
ROLES_FILE = REPO_ROOT / "docs" / "implementation" / "src_roles.yaml"


def _git_ls_files_src() -> list[str] | None:
    if not (REPO_ROOT / ".git").exists():
        return None
    try:
        proc = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "ls-files", "-z", "--", "src"],
            check=False,
            capture_output=True,
        )
    except OSError:
        return None
    if proc.returncode != 0:
        return None
    raw = proc.stdout or b""
    paths = [p.decode("utf-8", errors="replace") for p in raw.split(b"\0") if p]
    return sorted(paths)


def _walk_src() -> list[str]:
    out: list[str] = []
    if not SRC_ROOT.is_dir():
        return out
    for p in sorted(SRC_ROOT.rglob("*")):
        if p.is_file():
            rel = p.relative_to(REPO_ROOT).as_posix()
            out.append(rel)
    return sorted(out)


def _list_src_paths() -> list[str]:
    return _git_ls_files_src() or _walk_src()


def _load_roles() -> dict[str, str]:
    if yaml is None or not ROLES_FILE.is_file():
        return {}
    data: Any = yaml.safe_load(ROLES_FILE.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        return {}
    roles = data.get("roles")
    if not isinstance(roles, dict):
        return {}
    out: dict[str, str] = {}
    for k, v in roles.items():
        if isinstance(k, str) and isinstance(v, str) and v.strip():
            out[k.replace("\\", "/")] = v.strip()
    return out


def _impl_doc_path(src_rel: str) -> Path:
    """src/foo.py -> docs/implementation/src/foo.md"""
    if not src_rel.startswith("src/"):
        return IMPL_SRC / "invalid.md"
    rest = src_rel[4:]  # after "src/"
    if "/" in rest:
        parent, name = rest.rsplit("/", 1)
    else:
        parent, name = "", rest
    stem = Path(name).stem
    ext = Path(name).suffix
    if ext != ".py":
        return IMPL_SRC / rest  # not used for non-py
    md_name = stem + ".md"
    if parent:
        return IMPL_SRC / parent / md_name
    return IMPL_SRC / md_name


def _extract_role_from_impl_doc(md_path: Path) -> str | None:
    if not md_path.is_file():
        return None
    text = md_path.read_text(encoding="utf-8", errors="replace")
    marker = "## 职责概述"
    if marker not in text:
        return None
    after = text.split(marker, 1)[1]
    for line in after.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith("|") and "---" in stripped:
            continue
        if stripped.startswith("##"):
            break
        return stripped[:240]
    return None


def _role_for_path(src_rel: str, roles: dict[str, str]) -> str:
    key = src_rel.replace("\\", "/")
    if key in roles:
        return roles[key]
    if key.endswith(".py"):
        md = _impl_doc_path(key)
        extracted = _extract_role_from_impl_doc(md)
        if extracted:
            return extracted
        return "TODO"
    return "—"


def _impl_doc_status(src_rel: str) -> str:
    if not src_rel.startswith("src/"):
        return "—"
    rest = src_rel[4:]
    if not rest.endswith(".py"):
        return "N/A"
    md = _impl_doc_path(src_rel)
    return "yes" if md.is_file() else "no"


def build_markdown() -> str:
    paths = _list_src_paths()
    roles = _load_roles()
    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/generate_implementation_index.py; "
        "do not edit by hand -->",
        "",
        "# `src/` 实现索引（SRC_INDEX）",
        "",
        "本文件由脚本根据当前仓库中的 `src/` 路径**自动生成**，保证与目录树一致。",
        "「职责 / 摘要」列优先来自 [`src_roles.yaml`](src_roles.yaml)，其次来自对应",
        "[`docs/implementation/src/...`](./src/) 镜像文档中的 `## 职责概述`；",
        "Python 文件若仍无摘要则标为 **TODO**（请在 `src_roles.yaml` 或该文件的 "
        "`.md` 中补全）。",
        "",
        "| Path | Kind | ImplDoc | Role / Summary |",
        "|------|------|---------|----------------|",
    ]
    for rel in paths:
        kind = Path(rel).suffix or "(dir)"
        impl = _impl_doc_status(rel)
        role = _role_for_path(rel, roles)
        safe_role = role.replace("|", "\\|")
        lines.append(f"| `{rel}` | `{kind}` | {impl} | {safe_role} |")
    lines.extend(
        [
            "",
            "## 维护说明",
            "",
            "1. 增删或移动 `src/` 下文件后，在仓库根目录执行：",
            "   `python scripts/generate_implementation_index.py`",
            "2. 将变更后的 `SRC_INDEX.md` 与代码一并提交。",
            "3. `pre-commit` 会在相关路径变更时执行 `--check`；失败时运行上一命令后"
            "重提。",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if SRC_INDEX.md would change.",
    )
    args = parser.parse_args()
    content = build_markdown()
    if args.check:
        if not OUTPUT.is_file():
            sys.stderr.write(
                f"Missing {OUTPUT.relative_to(REPO_ROOT)}; "
                "run: python scripts/generate_implementation_index.py\n"
            )
            return 1
        existing = OUTPUT.read_text(encoding="utf-8")
        if existing != content:
            sys.stderr.write(
                f"{OUTPUT.relative_to(REPO_ROOT)} is stale. "
                "Run: python scripts/generate_implementation_index.py\n"
            )
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({OUTPUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
